del /s *.~*
del /s *.bak
del /s *.dcu
del /s *.cfg
del /s *.elf
del /s *.dpu
del /s *.dsk
del /s *.dof
del /s *.kof
del /s *.ddp
del /s *.mps
del /s *.mpt
del /s *.log
del /s *.so
del /s *.stat
del /s *.tci
del /s *.identcache
del /s *.dproj.local
del /s *.dproj
del /s /A Thumbs.db
